# use our LruIndex manager
client:
 type: lru
 lru:
    size: 10

# make sure we store these somewhere as the LruClient closes them locally
gateway:
  type: cassandra
  cassandra:
    host: localhost
    port: 9160
    keyspace: ElasticSearch

index:
  numberOfShards: 1
  numberOfReplicas: 0
  robin:
    refreshInterval: -1
  store:
    type: memory
