# use our LruIndex manager
client:
 type: org.elasticsearch.plugin.lruclient.LruClient

# make sure we store these somewhere as the LruClient closes them locally
gateway:
  type: cassandra

index:
  numberOfShards: 1
  numberOfReplicas: 0
  robin:
    refreshInterval: -1
