network:
  tcp:
    keep_alive: true

cluster:
  name: development

gateway:
  type: cassandra
  cassandra:
    host: localhost
    port: 9160
    keyspace: ElasticSearch

index:
  store:
    type: memory
  number_of_shards: 1
  number_of_replicas: 1
  robin:
    refreshInterval: -1

# use our LruIndex manager
client:
  type: lru
  lru:
    size: 10
