# use our LruIndex manager
client:
 type: lru
 lru:
    size: 10

# make sure we store these somewhere as the LruClient closes them locally
gateway:
  type: fs
  fs:
    # if you don't like the default work/ dif for long term storage
    location: /var/lib/elasticsearch

index:
  numberOfShards: 1
  numberOfReplicas: 0
  robin:
    refreshInterval: -1
